import fs from "node:fs";
import path from "node:path";
import { getStringOption, hasOption } from "../args.js";
import { readEnvFileIfExists } from "../env-utils.js";
import { readJsonFile, writeJson, writeText } from "../fs-utils.js";
import type { ServiceManifest } from "../types.js";
import { buildContextMarkdown, buildContextReplyMarkdown, buildContextReplyTemplate, buildContextRequestMarkdown, type ContextTemplate } from "./context.js";
import { writeDoctorReportFiles } from "./doctor.js";
import { buildReadinessMarkdown, buildReadinessSummary } from "./readiness.js";

interface HandoffFile {
  path: string;
  present: boolean;
  reason: string;
}

interface HandoffManifest {
  schema_version: "0.1";
  generated_at: string;
  package_path: string;
  target_service: string;
  recommended_files: HandoffFile[];
  optional_evidence_files: HandoffFile[];
  excluded_paths: HandoffFile[];
  warnings: string[];
  next_steps: string[];
}

interface HandoffFileSet {
  recommended: HandoffFileDefinition[];
  optional: HandoffFileDefinition[];
  excluded: HandoffFileDefinition[];
}

type HandoffFileDefinition = readonly [string, string];

interface SensitiveValue {
  key: string;
  value: string;
  source: string;
}

interface SensitiveContext {
  feishu_app?: {
    app_secret?: unknown;
    verification_token?: unknown;
    encrypt_key?: unknown;
  };
  runtime_config?: {
    debug_access_token?: unknown;
  };
}

interface GenericSecretFinding {
  path: string;
  kind: string;
}

interface SharedEvidenceFinding {
  path: string;
  kind: string;
}

interface HandoffInstructionFinding {
  path: string;
  kind: string;
}

interface StalePackagePathFinding {
  path: string;
  kind: string;
  value: string;
}

const GENERIC_SECRET_PATTERNS: Array<{ kind: string; pattern: RegExp }> = [
  { kind: "openai_api_key_literal", pattern: /\bsk-[A-Za-z0-9][A-Za-z0-9_-]{8,}\b/ },
  { kind: "env_secret_assignment", pattern: /^\s*(APP_SECRET|VERIFICATION_TOKEN|ENCRYPT_KEY|DEBUG_ACCESS_TOKEN)\s*=\s*(?!"?$)(?!<)[^\s#][^\r\n]*$/im },
  { kind: "json_secret_value", pattern: /"(app_secret|verification_token|encrypt_key|debug_access_token)"\s*:\s*"(?!<)[^"\r\n]{6,}"/i },
];

const BASE_RECOMMENDED_FILES = [
  [".gitignore", "Generated package local-file exclusions."],
  ["START_HERE.md", "Short first-entry guide for the next FDE or operator."],
  ["README.md", "Primary operator guide for the generated package."],
  ["deployment_checklist.md", "Step-by-step FDE checklist."],
  ["feishu_context.template.json", "Fillable external context template without real secrets."],
  ["feishu_context.template.md", "Human-readable context checklist for app owner/FDE values."],
  ["feishu_context.request.md", "Short owner-facing request that asks who can provide each external value, permission, and callback."],
  ["feishu_context.reply.template.json", "Safe non-secret owner reply template for context intake."],
  ["feishu_context.reply.template.md", "Human-readable non-secret owner reply template for context intake."],
  ["handoff_status.md", "Current missing-context and readiness summary."],
  ["level2_verification_record.md", "Final real Feishu evidence record to fill during Level 2."],
  ["level2_manual_evidence.template.json", "Safe template for collecting manual Feishu result evidence in an ignored local file."],
  ["manifest/service_manifest.json", "Machine-readable target service contract."],
  ["manifest/capability_map.json", "Machine-readable capability contract."],
  ["manifest/interaction_contract.json", "Machine-readable Lark interaction contract."],
  ["manifest/required_permissions.json", "Machine-readable permission contract."],
  ["adapter/handlers.ts", "Generated adapter action handlers."],
  ["adapter/cards.ts", "Generated Lark card builders for the adapter."],
  ["adapter/service-client.ts", "Generated target service client for the adapter."],
  ["adapter/validation.ts", "Generated adapter input validation."],
  ["adapter/types.ts", "Generated adapter TypeScript contracts."],
  ["adapter/audit-events.ts", "Generated adapter audit event helpers."],
] as const;

const OPTIONAL_EVIDENCE_FILES = [
  ["permission_review.md", "Feishu scopes, callbacks, and permission rationale."],
  ["doctor_report.md", "Human-readable MVP gate report generated by the doctor command."],
  ["doctor_report.json", "Machine-readable MVP gate report generated by the doctor command."],
  ["handoff_manifest.md", "Human-readable safe transfer manifest generated by the handoff command."],
  ["handoff_manifest.json", "Machine-readable safe transfer manifest generated by the handoff command."],
  ["verification_report.md", "Latest verification report; may include local paths but is useful for handoff."],
  ["verification_report.json", "Machine-readable verification report for readiness/evidence commands."],
  ["level2_evidence_draft.md", "Machine-generated evidence draft from report and audit log."],
  ["level2_verification_record.template.md", "Fresh blank Level 2 record template written when an existing evidence record is preserved during regeneration."],
  ["analysis_report.md", "Analyzer summary for review."],
  ["card_plan.md", "Generated card interaction plan."],
  ["context_readiness.md", "External-context readiness checklist."],
  ["generation_summary.json", "Generation metadata."],
  ["bot-runtime/package-lock.json", "Pinned runtime dependency tree, present after npm install."],
] as const;

const EXCLUDED_PATHS = [
  ["bot-runtime/.env", "Contains local secrets and runtime-specific values."],
  ["feishu_context.local.json", "Local filled context may contain Feishu secrets."],
  ["feishu_context.reply.local.json", "Local owner reply may include internal contact or deployment context."],
  ["feishu_context.reply.local.md", "Local owner reply may include internal contact or deployment context."],
  ["level2_manual_evidence.local.json", "Local manual Feishu evidence may include operator, chat, message, screenshot, and trace context."],
  ["configure_report.json", "Local configure report may include local machine paths and environment source context; regenerate after transfer."],
  ["configure_report.md", "Local configure report may include local machine paths and environment source context; regenerate after transfer."],
  ["bot-runtime/node_modules", "Dependency install output; regenerate with npm install."],
  ["bot-runtime/dist", "Build output; regenerate with npm run build."],
  ["bot-runtime/tmp", "Runtime scratch files."],
  ["bot-runtime/audit.log", "Runtime audit log may include operator/chat context and local evidence."],
  ["bot-runtime/*.log", "Runtime logs may contain local paths or sensitive operational context."],
  ["feishu-host/.env", "Contains local Feishu app credentials and target runtime values."],
  ["feishu-host/.venv", "Python virtualenv output; regenerate with pip install."],
  ["feishu-host/__pycache__", "Python bytecode cache; regenerate locally."],
] as const;

export async function handoffCommand(args: string[], options: Record<string, string | boolean>): Promise<void> {
  const packageArg = args[0];
  if (!packageArg) {
    throw new Error("Usage: lark-deployer handoff <generated-package> [--out <file>] [--copy-to <dir>] [--check]");
  }

  const packagePath = path.resolve(packageArg);
  const manifest = buildHandoffManifest(packagePath);
  const outFile = path.resolve(getStringOption(options, "out", path.join(packagePath, "handoff_manifest.json")));
  const markdownFile = outFile.replace(/\.json$/i, ".md");
  const copyTo = getStringOption(options, "copy-to", getStringOption(options, "copyTo", ""));
  const check = hasOption(options, "check");

  writeJson(outFile, manifest);
  writeText(markdownFile, buildHandoffMarkdown(manifest));
  if (copyTo) {
    const copyTargetPath = path.resolve(copyTo);
    const copied = copyHandoffPackage(packagePath, copyTargetPath, manifest, [outFile, markdownFile]);
    refreshCopiedHandoffReports(copyTargetPath);
    console.log(`Sanitized handoff copy written to ${copyTargetPath}`);
    console.log(`Copied files: ${copied}`);
    console.log("Refreshed context, verification, evidence, handoff, doctor, and Level 2 path references inside the copied package.");
  }
  if (check) {
    const checkPath = copyTo ? path.resolve(copyTo) : packagePath;
    const checkManifest = copyTo ? buildHandoffManifest(checkPath) : manifest;
    assertHandoffCheckPassed(checkPath, checkManifest);
    console.log(`Handoff check passed for ${checkPath}`);
  }
  printHandoffSummary(manifest, outFile, markdownFile);
}

function refreshCopiedHandoffReports(packagePath: string): void {
  const sourcePackagePathCandidates = collectSourcePackagePathCandidates(packagePath);
  refreshCopiedContextFiles(packagePath);
  refreshCopiedVerificationArtifacts(packagePath, sourcePackagePathCandidates);
  refreshCopiedLevel2RecordPaths(packagePath);
  const readinessSummary = buildReadinessSummary(packagePath, {});
  writeText(path.join(packagePath, "handoff_status.md"), buildReadinessMarkdown(readinessSummary));
  writeDoctorReportFiles(packagePath, path.join(packagePath, "doctor_report.json"));
  const targetManifest = buildHandoffManifest(packagePath);
  writeJson(path.join(packagePath, "handoff_manifest.json"), targetManifest);
  writeText(path.join(packagePath, "handoff_manifest.md"), buildHandoffMarkdown(targetManifest));
}

function refreshCopiedContextFiles(packagePath: string): void {
  const contextPath = path.join(packagePath, "feishu_context.template.json");
  if (!fs.existsSync(contextPath)) return;

  const context = readJsonFile<ContextTemplate>(contextPath);
  const refreshed: ContextTemplate = {
    ...context,
    handoff_request: {
      ...context.handoff_request,
      generated_package_hint: packagePath,
      verification_commands: copiedPackageCommands(),
      command_sets: copiedPackageCommandSets(packagePath),
    },
  };
  writeJson(contextPath, refreshed);
  writeText(path.join(packagePath, "feishu_context.template.md"), buildContextMarkdown(refreshed));
  writeText(path.join(packagePath, "feishu_context.request.md"), buildContextRequestMarkdown(refreshed));
  const replyTemplate = buildContextReplyTemplate(refreshed);
  writeJson(path.join(packagePath, "feishu_context.reply.template.json"), replyTemplate);
  writeText(path.join(packagePath, "feishu_context.reply.template.md"), buildContextReplyMarkdown(replyTemplate));
}

function copiedPackageCommandSets(packagePath: string): ContextTemplate["handoff_request"]["command_sets"] {
  const packageArg = quoteCommandArg(packagePath);
  return [
    {
      name: "project_root",
      cwd_hint: "Run from the Lark-deployer project root. The copied package path is absolute.",
      commands: [
        `node dist/index.js init-local ${packageArg} --context --reply`,
        `node dist/index.js configure ${packageArg} --strict --dry-run`,
        `node dist/index.js configure ${packageArg} --strict`,
        `node dist/index.js status ${packageArg}`,
        `node dist/index.js readiness ${packageArg}`,
        `node dist/index.js doctor ${packageArg}`,
        `node dist/index.js doctor ${packageArg} --gate`,
        `node dist/index.js doctor ${packageArg} --probe-target --gate`,
        `node dist/index.js verify ${packageArg}`,
        `node dist/index.js verify ${packageArg} --runtime-url http://127.0.0.1:3978 --simulate`,
        `node dist/index.js verify ${packageArg} --runtime-url http://127.0.0.1:3978 --level2`,
        `node dist/index.js evidence ${packageArg} --runtime-url http://127.0.0.1:3978 --update-record`,
        `node dist/index.js handoff ${packageArg}`,
      ],
    },
    {
      name: "generated_package_root",
      cwd_hint: "Run from this package root. Because this is a copied package, set LARK_DEPLOYER_CLI to the absolute path of the built Lark-deployer CLI.",
      commands: copiedPackageCommands(),
    },
    {
      name: "moved_package_root",
      cwd_hint: "Run from this package root after it has been copied elsewhere. Set LARK_DEPLOYER_CLI to the absolute path of the built Lark-deployer CLI.",
      commands: copiedPackageCommands(),
    },
  ];
}

function copiedPackageCommands(): string[] {
  return [
    "$env:LARK_DEPLOYER_CLI=\"C:\\path\\to\\Lark-deployer\\dist\\index.js\"",
    "node $env:LARK_DEPLOYER_CLI init-local . --context --reply",
    "node $env:LARK_DEPLOYER_CLI configure . --strict --dry-run",
    "node $env:LARK_DEPLOYER_CLI configure . --strict",
    "node $env:LARK_DEPLOYER_CLI status .",
    "node $env:LARK_DEPLOYER_CLI readiness .",
    "node $env:LARK_DEPLOYER_CLI doctor .",
    "node $env:LARK_DEPLOYER_CLI doctor . --gate",
    "node $env:LARK_DEPLOYER_CLI doctor . --probe-target --gate",
    "node $env:LARK_DEPLOYER_CLI verify . --runtime-url http://127.0.0.1:3978 --simulate",
    "node $env:LARK_DEPLOYER_CLI verify . --runtime-url http://127.0.0.1:3978 --level2",
    "node $env:LARK_DEPLOYER_CLI evidence . --runtime-url http://127.0.0.1:3978 --update-record",
    "node $env:LARK_DEPLOYER_CLI handoff .",
  ];
}

function quoteCommandArg(value: string): string {
  if (!value) return "\"\"";
  if (/[\s"'#]/.test(value)) return JSON.stringify(value);
  return value;
}

function refreshCopiedVerificationArtifacts(packagePath: string, sourcePackagePathCandidates: string[]): void {
  const verificationReportPath = path.join(packagePath, "verification_report.json");
  if (fs.existsSync(verificationReportPath)) {
    const report = readJsonFile<unknown>(verificationReportPath);
    writeJson(verificationReportPath, replacePackagePathStrings(report, sourcePackagePathCandidates, packagePath));
  }
  for (const relativePath of ["verification_report.md", "level2_evidence_draft.md"]) {
    const filePath = path.join(packagePath, relativePath);
    if (!fs.existsSync(filePath)) continue;
    let content = replacePackagePathText(fs.readFileSync(filePath, "utf8"), sourcePackagePathCandidates, packagePath);
    if (relativePath === "level2_evidence_draft.md") {
      content = redactLegacyManualEvidenceDraft(content);
    }
    writeText(filePath, content);
  }
}

function redactLegacyManualEvidenceDraft(content: string): string {
  return content
    .split(/\r?\n/)
    .map((line) => redactLegacyManualEvidenceRow(line))
    .join("\n");
}

function redactLegacyManualEvidenceRow(line: string): string {
  if (!line.trim().startsWith("|")) return line;
  const cells = line.split("|");
  if (cells.length < 5) return line;
  const sourceIndex = cells.length - 2;
  const source = cells[sourceIndex] || "";
  if (!isManualEvidenceSource(source)) return line;
  cells[2] = " provided (redacted in shared draft) ";
  cells[sourceIndex] = ` ${redactedManualEvidenceSource(source)} `;
  return cells.join("|");
}

function isManualEvidenceSource(source: string): boolean {
  return /manual evidence file|manual CLI options/i.test(source);
}

function redactedManualEvidenceSource(source: string): string {
  const hasFile = /manual evidence file/i.test(source);
  const hasCli = /manual CLI options/i.test(source);
  if (hasFile && hasCli) return "manual evidence file (redacted path) + manual CLI options";
  if (hasFile) return "manual evidence file (redacted path)";
  if (hasCli) return "manual CLI options";
  return "manual evidence";
}

function collectSourcePackagePathCandidates(packagePath: string): string[] {
  const candidates: string[] = [];
  const verificationReportPath = path.join(packagePath, "verification_report.json");
  if (fs.existsSync(verificationReportPath)) {
    try {
      const report = readJsonFile<unknown>(verificationReportPath);
      collectPathLikeStrings(report, candidates);
    } catch {
      // Ignore stale or malformed optional evidence; handoff --check will still scan copied text.
    }
  }
  const contextPath = path.join(packagePath, "feishu_context.template.json");
  if (fs.existsSync(contextPath)) {
    try {
      const context = readJsonFile<Partial<ContextTemplate>>(contextPath);
      const hint = context.handoff_request?.generated_package_hint;
      if (typeof hint === "string") candidates.push(hint);
    } catch {
      // Ignore malformed optional context here; other commands surface parse failures.
    }
  }

  for (const relativePath of ["verification_report.md", "level2_evidence_draft.md"]) {
    const filePath = path.join(packagePath, relativePath);
    if (!fs.existsSync(filePath)) continue;
    collectPathLikeMatches(fs.readFileSync(filePath, "utf8"), candidates);
  }

  return uniquePathCandidates(candidates, packagePath);
}

function collectPathLikeStrings(value: unknown, output: string[]): void {
  if (typeof value === "string") {
    collectPathLikeMatches(value, output);
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) collectPathLikeStrings(item, output);
    return;
  }
  if (value && typeof value === "object") {
    for (const item of Object.values(value)) collectPathLikeStrings(item, output);
  }
}

function collectPathLikeMatches(value: string, output: string[]): void {
  const windowsPathPattern = /[A-Za-z]:\\[^\r\n|`"]*?(?:image-agent-web-lark|[A-Za-z0-9_-]+-lark)(?=\\|$|[\s\r\n|`"])/g;
  for (const match of value.matchAll(windowsPathPattern)) {
    output.push(match[0]);
  }
  if (/\bgenerated\\image-agent-web-lark\b/.test(value)) {
    output.push("generated\\image-agent-web-lark");
  }
}

function uniquePathCandidates(candidates: string[], packagePath: string): string[] {
  const normalizedPackagePath = normalizePathCandidate(packagePath);
  const seen = new Set<string>();
  return candidates
    .map((candidate) => candidate.trim().replace(/[\\\/]+$/, ""))
    .filter((candidate) => candidate && normalizePathCandidate(candidate) !== normalizedPackagePath)
    .filter((candidate) => {
      const normalized = normalizePathCandidate(candidate);
      if (seen.has(normalized)) return false;
      seen.add(normalized);
      return true;
    })
    .sort((a, b) => b.length - a.length);
}

function normalizePathCandidate(value: string): string {
  return value.replace(/\//g, "\\").replace(/[\\]+$/g, "").toLowerCase();
}

function replacePackagePathStrings(value: unknown, sourcePackagePathCandidates: string[], packagePath: string): unknown {
  if (typeof value === "string") return replacePackagePathText(value, sourcePackagePathCandidates, packagePath);
  if (Array.isArray(value)) return value.map((item) => replacePackagePathStrings(item, sourcePackagePathCandidates, packagePath));
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [
      key,
      replacePackagePathStrings(item, sourcePackagePathCandidates, packagePath),
    ]));
  }
  return value;
}

function replacePackagePathText(content: string, sourcePackagePathCandidates: string[], packagePath: string): string {
  let updated = content;
  for (const candidate of sourcePackagePathCandidates) {
    updated = updated.split(candidate).join(packagePath);
    updated = updated.split(candidate.replace(/\\/g, "/")).join(packagePath.replace(/\\/g, "/"));
  }
  return updated;
}

function refreshCopiedLevel2RecordPaths(packagePath: string): void {
  const recordPath = path.join(packagePath, "level2_verification_record.md");
  if (!fs.existsSync(recordPath)) return;

  const replacements = [
    ["Generated package path", packagePath],
    ["`verification_report.md` path", path.join(packagePath, "verification_report.md")],
  ] as const;
  let record = fs.readFileSync(recordPath, "utf8");
  for (const [field, value] of replacements) {
    record = replaceRecordField(record, field, value);
  }
  record = refreshLevel2RecordCliGuidance(record);
  writeText(recordPath, record);
}

function replaceRecordField(record: string, field: string, value: string): string {
  const pattern = new RegExp(`^(-[^\\S\\r\\n]*${escapeRegExp(field)}:[^\\S\\r\\n]*)([^\\r\\n]*)$`, "im");
  return record.replace(pattern, (_line, prefix: string) => `${prefix.replace(/[^\S\r\n]*$/, " ")}${value}`);
}

function refreshLevel2RecordCliGuidance(record: string): string {
  let updated = record;
  if (!/^## CLI Command Style\s*$/im.test(updated)) {
    updated = updated.replace(
      /^## Preflight Evidence\s*$/im,
      `${level2RecordCliGuidance()}\n\n## Preflight Evidence`,
    );
  }
  updated = updated.replace(
    /- \[ \] `node \.\.\\\.\.\\dist\\index\.js verify \. --runtime-url <bot_runtime_url> --simulate` records card-action, v2 card-action, and invalid-input failure-card PASS checks\./g,
    "- [ ] `verify . --runtime-url <bot_runtime_url> --simulate` records card-action, v2 card-action, iterate, batch, batch-refresh, and invalid-input failure-card PASS checks using the command style above.",
  );
  updated = updated.replace(
    /- \[ \] `verify \. --runtime-url <bot_runtime_url> --simulate` records card-action, v2 card-action, and invalid-input failure-card PASS checks using the command style above\./g,
    "- [ ] `verify . --runtime-url <bot_runtime_url> --simulate` records card-action, v2 card-action, iterate, batch, batch-refresh, and invalid-input failure-card PASS checks using the command style above.",
  );
  updated = updated.replace(
    /- \[ \] `verify \. --runtime-url <bot_runtime_url> --simulate` records card-action, v2 card-action, iterate, and invalid-input failure-card PASS checks using the command style above\./g,
    "- [ ] `verify . --runtime-url <bot_runtime_url> --simulate` records card-action, v2 card-action, iterate, batch, batch-refresh, and invalid-input failure-card PASS checks using the command style above.",
  );
  updated = updated.replace(
    /- \[ \] `node \.\.\\\.\.\\dist\\index\.js verify \. --runtime-url <bot_runtime_url> --level2` succeeds\./g,
    "- [ ] `verify . --runtime-url <bot_runtime_url> --level2` succeeds using the command style above.",
  );
  return updated;
}

function level2RecordCliGuidance(): string {
  return `## CLI Command Style

- If this package still lives under the original Lark-deployer repository, run commands as \`node ..\\..\\dist\\index.js <command> .\`.
- If this package was copied elsewhere, set \`$env:LARK_DEPLOYER_CLI="C:\\path\\to\\Lark-deployer\\dist\\index.js"\` and run commands as \`node $env:LARK_DEPLOYER_CLI <command> .\`.`;
}

function buildHandoffManifest(packagePath: string): HandoffManifest {
  const service = readJsonFile<ServiceManifest>(path.join(packagePath, "manifest", "service_manifest.json"));
  const fileSet = buildHandoffFileSet(packagePath);
  const recommendedFiles = fileSet.recommended.map(([filePath, reason]) => fileRow(packagePath, filePath, reason));
  const optionalEvidenceFiles = fileSet.optional.map(([filePath, reason]) => fileRow(packagePath, filePath, reason));
  const excludedPaths = fileSet.excluded.map(([filePath, reason]) => fileRow(packagePath, filePath, reason));
  const warnings = buildWarnings(recommendedFiles, excludedPaths);

  return {
    schema_version: "0.1",
    generated_at: new Date().toISOString(),
    package_path: packagePath,
    target_service: service.service.name,
    recommended_files: recommendedFiles,
    optional_evidence_files: optionalEvidenceFiles,
    excluded_paths: excludedPaths,
    warnings,
    next_steps: [
      "Copy recommended files and directories, excluding all excluded paths.",
      "Or run `handoff --copy-to <empty-dir>` to create a sanitized transfer directory automatically.",
      "`handoff --copy-to` scans copied text files for known local secret values and refuses the copy if one is found.",
      "Run `handoff --check` on the sanitized directory; it also rejects missing configure dry-run guidance, missing init-local guidance, missing permission confirmation summaries, missing doctor live-target gate guidance, stale package path references, non-strict configure commands, and unredacted manual evidence rows in shared Level 2 drafts.",
      "Share real Feishu secrets through a secure channel, not in the package.",
      "Run `npm install` and `npm run build` inside `bot-runtime` after transfer.",
      "Run `readiness`, `verify --level2`, `evidence`, and `doctor --probe-target --gate` from the target environment before final sign-off.",
    ],
  };
}

function buildHandoffFileSet(packagePath: string): HandoffFileSet {
  return {
    recommended: requiredHandoffFiles(packagePath),
    optional: optionalHandoffFiles(packagePath),
    excluded: Array.from(EXCLUDED_PATHS),
  };
}

function requiredHandoffFiles(packagePath: string): HandoffFileDefinition[] {
  const rows = new Map<string, string>(BASE_RECOMMENDED_FILES);
  const imageMetaPath = "manifest/image_agent_meta.snapshot.json";
  if (pathExists(packagePath, imageMetaPath)) {
    rows.set(imageMetaPath, "Template metadata snapshot used by generated cards.");
  }
  for (const dir of ["adapter", "bot-runtime", "feishu-host", "sidecar-long-connection"]) {
    const absoluteDir = path.join(packagePath, dir);
    if (!fs.existsSync(absoluteDir) || !fs.statSync(absoluteDir).isDirectory()) continue;
    for (const filePath of listPackageFiles(absoluteDir)) {
      const relativePath = toForwardSlash(path.join(dir, filePath));
      if (!isExcluded(relativePath)) {
        rows.set(relativePath, generatedClosureReason(dir));
      }
    }
  }
  return Array.from(rows.entries());
}

function optionalHandoffFiles(packagePath: string): HandoffFileDefinition[] {
  return OPTIONAL_EVIDENCE_FILES.filter(([filePath]) => pathExists(packagePath, filePath));
}

function generatedClosureReason(dir: string): string {
  if (dir === "adapter") return "Generated adapter runtime closure.";
  if (dir === "bot-runtime") return "Generated standalone reference runtime closure.";
  if (dir === "feishu-host") return "Generated self-hosted Feishu host module closure.";
  return "Generated sidecar or gateway host contract closure.";
}

function fileRow(packagePath: string, relativePath: string, reason: string): HandoffFile {
  return {
    path: relativePath,
    present: pathExists(packagePath, relativePath),
    reason,
  };
}

function pathExists(packagePath: string, relativePath: string): boolean {
  if (relativePath.includes("*")) {
    const dir = path.dirname(relativePath);
    const basename = path.basename(relativePath).replace(/\*/g, "");
    const absoluteDir = path.join(packagePath, dir);
    return fs.existsSync(absoluteDir) && fs.readdirSync(absoluteDir).some((entry) => entry.endsWith(basename));
  }
  return fs.existsSync(path.join(packagePath, relativePath));
}

function copyHandoffPackage(
  packagePath: string,
  targetPath: string,
  manifest: HandoffManifest,
  generatedManifestFiles: string[],
): number {
  assertCopyTarget(packagePath, targetPath);
  fs.mkdirSync(targetPath, { recursive: true });

  const relativeFiles = new Set([
    ...manifest.recommended_files.filter((item) => item.present).map((item) => item.path),
    ...manifest.optional_evidence_files.filter((item) => item.present).map((item) => item.path),
  ]);
  for (const generatedFile of generatedManifestFiles) {
    const relative = toRelativeInside(packagePath, generatedFile);
    if (relative) relativeFiles.add(relative);
  }

  assertNoSensitiveLeaks(packagePath, Array.from(relativeFiles).sort());
  let copied = 0;
  for (const relativePath of Array.from(relativeFiles).sort()) {
    if (isExcluded(relativePath)) continue;
    const source = path.join(packagePath, relativePath);
    if (!fs.existsSync(source) || fs.statSync(source).isDirectory()) continue;
    const target = path.join(targetPath, relativePath);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(source, target);
    copied += 1;
  }
  return copied;
}

function assertNoSensitiveLeaks(packagePath: string, relativeFiles: string[]): void {
  const sensitiveValues = collectSensitiveValues(packagePath);
  if (!sensitiveValues.length) return;

  const leaks: Array<{ file: string; key: string; source: string }> = [];
  for (const relativePath of relativeFiles) {
    if (isExcluded(relativePath)) continue;
    const source = path.join(packagePath, relativePath);
    if (!fs.existsSync(source) || fs.statSync(source).isDirectory() || !isTextFile(relativePath)) continue;
    const content = fs.readFileSync(source, "utf8");
    for (const item of sensitiveValues) {
      if (containsSensitiveValue(content, item.value)) {
        leaks.push({ file: relativePath, key: item.key, source: item.source });
      }
    }
  }

  if (leaks.length) {
    const details = leaks
      .map((item) => `${item.file} contains ${item.key} from ${item.source}`)
      .join("; ");
    throw new Error(`Refusing sanitized handoff copy because copied files contain local secret values: ${details}. Remove or redact these values before rerunning handoff.`);
  }
}

function assertHandoffCheckPassed(packagePath: string, manifest: HandoffManifest): void {
  const missingRecommended = manifest.recommended_files.filter((item) => !item.present);
  const presentExcluded = manifest.excluded_paths.filter((item) => item.present);
  const genericSecrets = scanGenericSecretLiterals(packagePath);
  const unredactedEvidence = scanUnredactedSharedEvidence(packagePath);
  const nonStrictConfigureCommands = scanNonStrictConfigureCommands(packagePath);
  const missingConfigureDryRunGuidance = scanMissingConfigureDryRunGuidance(packagePath);
  const missingInitLocalGuidance = scanMissingInitLocalGuidance(packagePath);
  const missingPermissionConfirmationGuidance = scanMissingPermissionConfirmationGuidance(packagePath);
  const missingDoctorProbeTargetGateGuidance = scanMissingDoctorProbeTargetGateGuidance(packagePath);
  const stalePackagePathReferences = scanStalePackagePathReferences(packagePath);
  const failures: string[] = [];

  if (missingRecommended.length) {
    failures.push(`missing recommended files: ${missingRecommended.map((item) => item.path).join(", ")}`);
  }
  if (presentExcluded.length) {
    failures.push(`excluded paths are present: ${presentExcluded.map((item) => item.path).join(", ")}`);
  }
  if (genericSecrets.length) {
    failures.push(`potential secret literals found: ${genericSecrets.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (unredactedEvidence.length) {
    failures.push(`unredacted shared evidence rows found: ${unredactedEvidence.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (nonStrictConfigureCommands.length) {
    failures.push(`non-strict configure commands found: ${nonStrictConfigureCommands.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (missingConfigureDryRunGuidance.length) {
    failures.push(`missing configure dry-run guidance: ${missingConfigureDryRunGuidance.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (missingInitLocalGuidance.length) {
    failures.push(`missing init-local guidance: ${missingInitLocalGuidance.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (missingPermissionConfirmationGuidance.length) {
    failures.push(`missing permission confirmation guidance: ${missingPermissionConfirmationGuidance.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (missingDoctorProbeTargetGateGuidance.length) {
    failures.push(`missing doctor live target gate guidance: ${missingDoctorProbeTargetGateGuidance.map((item) => `${item.path} (${item.kind})`).join(", ")}`);
  }
  if (stalePackagePathReferences.length) {
    failures.push(`stale package path references found: ${stalePackagePathReferences.map((item) => `${item.path} (${item.kind}: ${item.value})`).join(", ")}`);
  }

  if (failures.length) {
    throw new Error(`Handoff check failed for ${packagePath}: ${failures.join("; ")}.`);
  }
}

function scanGenericSecretLiterals(packagePath: string): GenericSecretFinding[] {
  const findings: GenericSecretFinding[] = [];
  for (const relativePath of listPackageFiles(packagePath)) {
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const content = fs.readFileSync(filePath, "utf8");
    for (const { kind, pattern } of GENERIC_SECRET_PATTERNS) {
      pattern.lastIndex = 0;
      if (pattern.test(content)) {
        findings.push({ path: relativePath, kind });
      }
    }
  }
  return findings;
}

function scanUnredactedSharedEvidence(packagePath: string): SharedEvidenceFinding[] {
  const relativePath = "level2_evidence_draft.md";
  const filePath = path.join(packagePath, relativePath);
  if (!fs.existsSync(filePath)) return [];

  const findings: SharedEvidenceFinding[] = [];
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const finding = findUnredactedManualEvidenceRow(line);
    if (finding) findings.push({ path: relativePath, kind: finding });
  }
  return dedupeEvidenceFindings(findings);
}

function findUnredactedManualEvidenceRow(line: string): string {
  if (!line.trim().startsWith("|")) return "";
  const cells = line.split("|");
  if (cells.length < 5) return "";
  const suppliedValue = (cells[2] || "").trim();
  const sourceIndex = cells.length - 2;
  const source = (cells[sourceIndex] || "").trim();
  if (!isManualEvidenceSource(source)) return "";
  if (!/provided \(redacted in shared draft\)/i.test(suppliedValue)) return "manual_evidence_value_not_redacted";
  if (/manual evidence file/i.test(source) && !/manual evidence file \(redacted path\)/i.test(source)) {
    return "manual_evidence_source_path_not_redacted";
  }
  return "";
}

function dedupeEvidenceFindings(findings: SharedEvidenceFinding[]): SharedEvidenceFinding[] {
  const seen = new Set<string>();
  return findings.filter((item) => {
    const id = `${item.path}\0${item.kind}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  });
}

function scanNonStrictConfigureCommands(packagePath: string): HandoffInstructionFinding[] {
  const findings: HandoffInstructionFinding[] = [];
  for (const relativePath of listPackageFiles(packagePath)) {
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const content = fs.readFileSync(filePath, "utf8");
    if (containsNonStrictConfigureCommand(content)) {
      findings.push({ path: relativePath, kind: "configure_without_strict" });
    }
  }
  return dedupeInstructionFindings(findings);
}

function scanMissingConfigureDryRunGuidance(packagePath: string): HandoffInstructionFinding[] {
  let hasConfigureCommand = false;
  let hasDryRunConfigureCommand = false;
  for (const relativePath of listPackageFiles(packagePath)) {
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const content = fs.readFileSync(filePath, "utf8");
    for (const line of content.split(/\r?\n/)) {
      if (!isConfigureCommandLine(line)) continue;
      hasConfigureCommand = true;
      if (containsConfigureDryRun(line)) {
        hasDryRunConfigureCommand = true;
      }
    }
  }
  if (!hasConfigureCommand || hasDryRunConfigureCommand) return [];
  return [{ path: "package", kind: "configure_dry_run_missing" }];
}

function scanMissingInitLocalGuidance(packagePath: string): HandoffInstructionFinding[] {
  let hasContextTemplate = false;
  let hasInitLocalContextReplyCommand = false;
  for (const relativePath of listPackageFiles(packagePath)) {
    if (relativePath === "feishu_context.template.json") {
      hasContextTemplate = true;
    }
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const content = fs.readFileSync(filePath, "utf8");
    if (containsInitLocalContextReplyCommand(content)) {
      hasInitLocalContextReplyCommand = true;
    }
  }
  if (!hasContextTemplate || hasInitLocalContextReplyCommand) return [];
  return [{ path: "package", kind: "init_local_context_reply_missing" }];
}

function scanMissingPermissionConfirmationGuidance(packagePath: string): HandoffInstructionFinding[] {
  if (!replyTemplateHasPermissionConfirmations(packagePath)) return [];
  for (const relativePath of listPackageFiles(packagePath)) {
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const content = fs.readFileSync(filePath, "utf8");
    if (/Permission confirmations/i.test(content)) return [];
  }
  return [{ path: "package", kind: "permission_confirmation_summary_missing" }];
}

function scanMissingDoctorProbeTargetGateGuidance(packagePath: string): HandoffInstructionFinding[] {
  for (const relativePath of listPackageFiles(packagePath)) {
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const content = fs.readFileSync(filePath, "utf8");
    if (containsDoctorProbeTargetGateCommand(content)) return [];
  }
  return [{ path: "package", kind: "doctor_probe_target_gate_missing" }];
}

function containsInitLocalContextReplyCommand(content: string): boolean {
  return content
    .split(/\r?\n/)
    .some((line) => /\binit-local\b/.test(line) && /(^|[\s"`'])--context(?=[\s"`',.]|$)/.test(line) && /(^|[\s"`'])--reply(?=[\s"`',.]|$)/.test(line));
}

function containsDoctorProbeTargetGateCommand(content: string): boolean {
  return content
    .split(/\r?\n/)
    .some((line) => isDoctorCommandLine(line)
      && /(^|[\s"`'])--gate(?=[\s"`',.]|$)/.test(line)
      && /(^|[\s"`'])--probe-target(?=[\s"`',.]|$)/.test(line));
}

function replyTemplateHasPermissionConfirmations(packagePath: string): boolean {
  const templatePath = path.join(packagePath, "feishu_context.reply.template.json");
  if (!fs.existsSync(templatePath)) return false;
  try {
    const parsed = readJsonFile<unknown>(templatePath);
    if (!isRecord(parsed) || !Array.isArray(parsed.permission_confirmations)) return false;
    return parsed.permission_confirmations.some((item) => isRecord(item) && typeof item.item === "string" && item.item.trim());
  } catch {
    return false;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function containsNonStrictConfigureCommand(content: string): boolean {
  return content
    .split(/\r?\n/)
    .some((line) => isConfigureCommandLine(line) && !/(^|[\s"`'])--strict(?=[\s"`',.]|$)/.test(line));
}

function containsConfigureDryRun(line: string): boolean {
  return /(^|[\s"`'])--dry-run(?=[\s"`',.]|$)/.test(line) || /(^|[\s"`'])--dryRun(?=[\s"`',.]|$)/.test(line);
}

function isConfigureCommandLine(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed || !/\bnode\s+/.test(trimmed) || !/\bconfigure\b/.test(trimmed)) return false;
  return /(?:dist\/index\.js|dist\\index\.js|index\.js|\$env:LARK_DEPLOYER_CLI)/.test(trimmed);
}

function isDoctorCommandLine(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed || !/\bnode\s+/.test(trimmed) || !/\bdoctor\b/.test(trimmed)) return false;
  return /(?:dist\/index\.js|dist\\index\.js|index\.js|\$env:LARK_DEPLOYER_CLI)/.test(trimmed);
}

function dedupeInstructionFindings(findings: HandoffInstructionFinding[]): HandoffInstructionFinding[] {
  const seen = new Set<string>();
  return findings.filter((item) => {
    const id = `${item.path}\0${item.kind}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  });
}

function scanStalePackagePathReferences(packagePath: string): StalePackagePathFinding[] {
  const findings: StalePackagePathFinding[] = [];
  const contextPath = path.join(packagePath, "feishu_context.template.json");
  if (fs.existsSync(contextPath)) {
    try {
      const context = readJsonFile<Partial<ContextTemplate>>(contextPath);
      const hint = context.handoff_request?.generated_package_hint;
      if (typeof hint === "string" && hint.trim() && !packageReferenceMatchesCurrent(hint, packagePath)) {
        findings.push({ path: "feishu_context.template.json", kind: "generated_package_hint_stale", value: hint });
      }
    } catch {
      // Other commands surface malformed context files; stale path scanning stays best-effort.
    }
  }

  for (const relativePath of listPackageFiles(packagePath)) {
    if (isExcluded(relativePath) || !isTextFile(relativePath)) continue;
    const filePath = path.join(packagePath, relativePath);
    const candidates: string[] = [];
    collectPathLikeMatches(fs.readFileSync(filePath, "utf8"), candidates);
    for (const candidate of uniquePathCandidates(candidates, "")) {
      if (!packageReferenceMatchesCurrent(candidate, packagePath)) {
        findings.push({ path: relativePath, kind: "stale_package_path", value: candidate });
      }
    }
  }

  return dedupeStalePackagePathFindings(findings);
}

function packageReferenceMatchesCurrent(reference: string, packagePath: string): boolean {
  const trimmed = reference.trim().replace(/[\\\/]+$/, "");
  if (!trimmed) return true;

  const normalizedReference = normalizePathCandidate(trimmed);
  const normalizedPackagePath = normalizePathCandidate(packagePath);
  if (normalizedReference === normalizedPackagePath) return true;

  if (isDefaultGeneratedPackageReference(trimmed, packagePath)) return true;

  if (!path.isAbsolute(trimmed)) {
    if (normalizePathCandidate(path.resolve(trimmed)) === normalizedPackagePath) return true;
    if (normalizePathCandidate(path.resolve(packagePath, trimmed)) === normalizedPackagePath) return true;
  }

  return false;
}

function isDefaultGeneratedPackageReference(reference: string, packagePath: string): boolean {
  return normalizePathCandidate(reference) === "generated\\image-agent-web-lark"
    && path.basename(packagePath).toLowerCase() === "image-agent-web-lark"
    && path.basename(path.dirname(packagePath)).toLowerCase() === "generated";
}

function dedupeStalePackagePathFindings(findings: StalePackagePathFinding[]): StalePackagePathFinding[] {
  const seen = new Set<string>();
  return findings.filter((item) => {
    const id = `${item.path}\0${item.kind}\0${normalizePathCandidate(item.value)}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  });
}

function listPackageFiles(packagePath: string): string[] {
  const files: string[] = [];
  const stack = [packagePath];
  while (stack.length) {
    const current = stack.pop() || "";
    if (!current || !fs.existsSync(current)) continue;
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const absolute = path.join(current, entry.name);
      const relative = toForwardSlash(path.relative(packagePath, absolute));
      if (entry.isDirectory()) {
        if (!isExcluded(relative)) {
          stack.push(absolute);
        }
        continue;
      }
      if (entry.isFile()) {
        files.push(relative);
      }
    }
  }
  return files.sort();
}

function collectSensitiveValues(packagePath: string): SensitiveValue[] {
  const values: SensitiveValue[] = [];
  const envPath = path.join(packagePath, "bot-runtime", ".env");
  const env = readEnvFileIfExists(envPath);
  for (const key of ["APP_SECRET", "VERIFICATION_TOKEN", "ENCRYPT_KEY", "DEBUG_ACCESS_TOKEN"]) {
    addSensitiveValue(values, key, env[key], "bot-runtime/.env");
  }

  collectSensitiveContextValues(values, packagePath, "feishu_context.local.json");
  collectSensitiveContextValues(values, packagePath, "feishu_context.template.json");
  return dedupeSensitiveValues(values);
}

function collectSensitiveContextValues(values: SensitiveValue[], packagePath: string, relativePath: string): void {
  const filePath = path.join(packagePath, relativePath);
  if (!fs.existsSync(filePath)) return;
  let context: SensitiveContext;
  try {
    context = readJsonFile<SensitiveContext>(filePath);
  } catch {
    return;
  }

  addSensitiveValue(values, "feishu_app.app_secret", context.feishu_app?.app_secret, relativePath);
  addSensitiveValue(values, "feishu_app.verification_token", context.feishu_app?.verification_token, relativePath);
  addSensitiveValue(values, "feishu_app.encrypt_key", context.feishu_app?.encrypt_key, relativePath);
  addSensitiveValue(values, "runtime_config.debug_access_token", context.runtime_config?.debug_access_token, relativePath);
}

function addSensitiveValue(values: SensitiveValue[], key: string, value: unknown, source: string): void {
  if (typeof value !== "string") return;
  const trimmed = value.trim();
  if (trimmed.length < 6 || looksLikePlaceholder(trimmed)) return;
  values.push({ key, value: trimmed, source });
}

function containsSensitiveValue(content: string, value: string): boolean {
  if (!/^[A-Za-z0-9_=-]+$/.test(value)) return content.includes(value);
  const escaped = escapeRegExp(value);
  return new RegExp(`(^|[^A-Za-z0-9_=-])${escaped}($|[^A-Za-z0-9_=-])`).test(content);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function looksLikePlaceholder(value: string): boolean {
  return /^<.*>$/.test(value) || value.toLowerCase().includes("placeholder");
}

function dedupeSensitiveValues(values: SensitiveValue[]): SensitiveValue[] {
  const seen = new Set<string>();
  return values.filter((item) => {
    const id = `${item.key}\0${item.value}\0${item.source}`;
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  });
}

function isTextFile(relativePath: string): boolean {
  return /\.(json|md|txt|ts|js|mjs|cjs|yml|yaml|toml|env|gitignore)$/i.test(relativePath)
    || !path.extname(relativePath);
}

function assertCopyTarget(packagePath: string, targetPath: string): void {
  if (path.resolve(packagePath) === path.resolve(targetPath)) {
    throw new Error("--copy-to must not point at the generated package itself.");
  }
  const relativeFromPackage = path.relative(packagePath, targetPath);
  if (relativeFromPackage && !relativeFromPackage.startsWith("..") && !path.isAbsolute(relativeFromPackage)) {
    throw new Error("--copy-to must not be inside the generated package; choose a separate empty directory.");
  }
  if (fs.existsSync(targetPath) && fs.readdirSync(targetPath).length > 0) {
    throw new Error(`--copy-to target already exists and is not empty: ${targetPath}`);
  }
}

function toRelativeInside(packagePath: string, filePath: string): string {
  const relative = path.relative(packagePath, filePath);
  if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) return "";
  return toForwardSlash(relative);
}

function isExcluded(relativePath: string): boolean {
  const normalized = toForwardSlash(relativePath);
  return normalized === "bot-runtime/.env"
    || normalized === "feishu_context.local.json"
    || normalized === "feishu_context.reply.local.json"
    || normalized === "feishu_context.reply.local.md"
    || normalized === "level2_manual_evidence.local.json"
    || normalized.startsWith("bot-runtime/node_modules/")
    || normalized === "bot-runtime/node_modules"
    || normalized.startsWith("bot-runtime/dist/")
    || normalized === "bot-runtime/dist"
    || normalized.startsWith("bot-runtime/tmp/")
    || normalized === "bot-runtime/tmp"
    || normalized === "bot-runtime/audit.log"
    || normalized.startsWith("bot-runtime/") && normalized.endsWith(".log")
    || normalized === "feishu-host/.env"
    || normalized.startsWith("feishu-host/.venv/")
    || normalized === "feishu-host/.venv"
    || normalized.startsWith("feishu-host/__pycache__/")
    || normalized === "feishu-host/__pycache__"
    || normalized.startsWith("feishu-host/") && normalized.endsWith(".pyc");
}

function toForwardSlash(value: string): string {
  return value.replace(/\\/g, "/");
}

function buildWarnings(recommendedFiles: HandoffFile[], excludedPaths: HandoffFile[]): string[] {
  const warnings: string[] = [];
  const missingRecommended = recommendedFiles.filter((item) => !item.present);
  if (missingRecommended.length) {
    warnings.push(`Missing recommended files: ${missingRecommended.map((item) => item.path).join(", ")}.`);
  }
  const presentExcluded = excludedPaths.filter((item) => item.present);
  if (presentExcluded.length) {
    warnings.push(`Excluded local/sensitive paths currently exist and must not be copied: ${presentExcluded.map((item) => item.path).join(", ")}.`);
  }
  return warnings;
}

function buildHandoffMarkdown(manifest: HandoffManifest): string {
  return `# Handoff Manifest

- Generated at: ${manifest.generated_at}
- Package: ${manifest.package_path}
- Target service: ${manifest.target_service}

## Recommended Files

${table(manifest.recommended_files)}

## Optional Evidence Files

${table(manifest.optional_evidence_files)}

## Excluded Paths

Do not copy these into a shared package unless a reviewer explicitly asks for them.

${table(manifest.excluded_paths)}

## Warnings

${manifest.warnings.length ? manifest.warnings.map((item) => `- ${item}`).join("\n") : "- none"}

## Next Steps

${manifest.next_steps.map((item) => `- ${item}`).join("\n")}
`;
}

function table(rows: HandoffFile[]): string {
  return [
    "| Present | Path | Reason |",
    "| --- | --- | --- |",
    ...rows.map((row) => `| ${row.present ? "yes" : "no"} | \`${row.path}\` | ${row.reason.replace(/\|/g, "\\|")} |`),
  ].join("\n");
}

function printHandoffSummary(manifest: HandoffManifest, outFile: string, markdownFile: string): void {
  const missing = manifest.recommended_files.filter((item) => !item.present).length;
  const excludedPresent = manifest.excluded_paths.filter((item) => item.present).length;
  console.log(`Handoff manifest written to ${outFile}`);
  console.log(`Handoff checklist written to ${markdownFile}`);
  console.log(`Recommended files missing: ${missing}`);
  console.log(`Excluded paths currently present: ${excludedPresent}`);
  if (manifest.warnings.length) {
    console.log(`Warnings: ${manifest.warnings.length}`);
  }
}
